### ISSUE TITLE
Use SAM Local for real testing of lambda code.

### ISSUE THREAD

**Issue by KempfCreative** [MaisonetteWorld/magine#18]
We should be able to test Lambda functions with a reasonable level of confidence. SAM Local seems to be the way to do that going forward. I would welcome a conversation here about the correct governance process for building/deploying/testing lambdas: @DanRoestorf .

**Comment by DanRoestorf** [comment]
SAM seemed great from the webinar I attended last week! I'm working on a quick and easy Lambda for syncing S3 buckets today, so I'll use SAM and test out its features so we can have a more robust conversation around its capabilities.
