### ISSUE TITLE
Image Encodings not linked to ImageMagick

### ISSUE THREAD

**Issue by KempfCreative** [MaisonetteWorld/magine#29]
Using `bash install.sh` to install a fresh copy of the image encodings to the Docker image, and then running `./configure` on ImageMagick results in not all of the image encodings being linked to the ImageMagick binary:
```
configure:
==============================================================================
ImageMagick is configured as follows. Please verify that this configuration
matches your expectations.

  Host system type: x86_64-pc-linux-gnu
  Build system type: x86_64-pc-linux-gnu

                 Option                        Value
  ------------------------------------------------------------------------------
  Shared libraries  --enable-shared=yes		yes
  Static libraries  --enable-static=yes		yes
  Build utilities   --with-utilities=yes        yes
  Module support    --with-modules=no		no
  GNU ld            --with-gnu-ld=yes		yes
  Quantum depth     --with-quantum-depth=16	16
  High Dynamic Range Imagery
                    --enable-hdri=yes		yes

  Install documentation:			yes

  Delegate Library Configuration:
  BZLIB             --with-bzlib=yes		no
  Autotrace         --with-autotrace=no		no
  DJVU              --with-djvu=yes		no
  DPS               --with-dps=yes		no
  FFTW              --with-fftw=yes		no
  FLIF              --with-flif=yes		no
  FlashPIX          --with-fpx=yes		yes
  FontConfig        --with-fontconfig=yes	no
  FreeType          --with-freetype=yes		no
  Ghostscript lib   --with-gslib=no		no
  Graphviz          --with-gvc=yes		no
  HEIC              --with-heic=yes             no
  JBIG              --with-jbig=yes		no
  JPEG v1           --with-jpeg=yes		yes
  LCMS              --with-lcms=yes		no
  LQR               --with-lqr=yes		no
  LTDL              --with-ltdl=yes		no
  LZMA              --with-lzma=yes		no
  Magick++          --with-magick-plus-plus=yes	yes
  OpenEXR           --with-openexr=yes		no
  OpenJP2           --with-openjp2=yes		no
  PANGO             --with-pango=yes		no
  PERL              --with-perl=no		no
  PNG               --with-png=yes		no
  RAQM              --with-raqm=yes		no
  RAW               --with-raw=yes 	   	no
  RSVG              --with-rsvg=no		no
  TIFF              --with-tiff=yes		yes
  WEBP              --with-webp=yes		no
  WMF               --with-wmf=yes		no
  X11               --with-x=			no
  XML               --with-xml=yes		no
  ZLIB              --with-zlib=yes		no
  ZSTD              --with-zstd=yes		no

  Delegate Program Configuration:
  GhostPCL          None				pcl6 (unknown)
  GhostXPS          None				gxps (unknown)
  Ghostscript       None				gs (unknown)

  Font Configuration:
  Apple fonts       --with-apple-font-dir=default
  Dejavu fonts      --with-dejavu-font-dir=default	none
  Ghostscript fonts --with-gs-font-dir=default	none
  URW-base35 fonts  --with-urw-base35-font-dir=default  none
  Windows fonts     --with-windows-font-dir=default	none

  X11 Configuration:
        X_CFLAGS        =
        X_PRE_LIBS      =
        X_LIBS          =
        X_EXTRA_LIBS    =

  Options used to compile and link:
    PREFIX          = /usr/local
    EXEC-PREFIX     = /usr/local
    VERSION         = 7.0.8
    CC              = gcc
    CFLAGS          =  -fopenmp -g -O2 -Wall -mtune=core2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
    CPPFLAGS        =   -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
    PCFLAGS         =
    DEFS            = -DHAVE_CONFIG_H
    LDFLAGS         =
    LIBS            =    -ltiff   -ljpeg        -lfpx                         -lm
    CXX             = g++
    CXXFLAGS        = -g -O2 -pthread
    FEATURES        = DPC HDRI Cipher OpenMP
    DELEGATES       = mpeg fpx jpeg tiff
==============================================================================
```

Based on the manual installation of PNG and WebP, those delegates should also exist in this ImageMagick package, yet they do not.

**Comment by blocknotes** [comment]
@KempfCreative: do we really need to recompile ImageMagick?

PNG is already enabled in the default package, WebP should work using a delegate, I just tried in a preview container:
`convert -list delegate | grep webp`
The output is:
`png<= webp      "cwebp' -quiet %Q '%i' -o '%o"`

So when you install the `webp` package it should work.
I made a simple test `convert src/images/about-1.png /tmp/test.webp` and it seems fine.

What do you think?

**Comment by KempfCreative** [comment]
@blocknotes we are compiling ImageMagick against the AWS container, as this project lives inside a Lambda environment. Each delegate should be manually found by the ImageMagick installation, as we are creating an ImageMagick 7 binary from scratch. 

I am assuming that you were testing against an ImageMagick 6 binary, as the commands have been converted to use `magick ...` for all of the previous commands ( `convert`, `mogrify`, etc... ).

**Comment by blocknotes** [comment]
@KempfCreative: I made some tests... if you install libpng and libwebp it works - but I don't know if there's a specific reason for you to compile them too.

In Dockerfile:
`RUN yum -y install libpng-devel libwebp-devel`
Then commented out the libpng and libwebp compilation.

In the end:
`magick -list format | grep -i webp`
outputs:
`WEBP* rw-   WebP Image Format (libwebp 0.3.0 [0201])`

Let me know, I can prepare a PR or I can make more inspection to see if we can build the 2 libraries too.

**Comment by KempfCreative** [comment]
@blocknotes I would be interested to know why the manual build didn't link the delegates, but that is more for my own curiosity. If your time is running low on working on this, I want to respect it, so I would be happy to accept a PR. If you want to continue investigating, I would also celebrate that.

You decide how you want to handle this 👍

**Comment by blocknotes** [comment]
Solved. I'm closing this one
