### ISSUE TITLE
Publish Response to SNS for consumption

### ISSUE THREAD

**Issue by KempfCreative** [MaisonetteWorld/magine#33]
The response from the Magine application should be able to be sent to a SNS topic or other PUB/SUB layer. This is because unless the lambda is triggered directly, the response is sent into the ether, unable to be consumed by anything useful.

**Comment by KempfCreative** [comment]
@DanRoestorf let me know if you need clarification here.

**Comment by DanRoestorf** [comment]
If we need the CMS or any other service to be notified by Magine's status SNS works nicely. The gist:
* We can send a POST request to any HTTP/S endpoint using SNS
* Requests can be authorized with Basic and Digest Access Authentication or Server Name Indication
* The endpoint needs to handle an initial subscription request to confirm its subscription to the topic
* After subscription confirmation simply publish to the SNS topic and requests will be sent to the endpoint

For more detail [here is the implementation guide.](https://docs.aws.amazon.com/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html)

Should I get this in place for the CMS @KempfCreative ?

**Comment by KempfCreative** [comment]
@DanRoestorf this sounds great. Please do the work needed to set this up and let me know if you need any implementation details.

**Comment by DanRoestorf** [comment]
Here's a quick architecture diagram for reference.

![magine](https://user-images.githubusercontent.com/44172434/60031345-90208800-9672-11e9-9151-c9039bede4c9.png)

**Comment by DanRoestorf** [comment]
@KempfCreative I was testing this locally using `ngrok` and `netcat`. I ran `ngrok http 9000` with `nc -l 9000` to record requests coming in. You can use `ngrok` to open up any local server to the outside world and are given a link that is forwared, for example: `Forwarding http://ea0c4a45.ngrok.io -> http://localhost:9000`. 

The endpoint will need to handle the first `SubscriptionConfirmation` request. Doing a GET request to the `SubscribeURL` will confirm that this endpoint should recieve notifications published to the topic.

```
POST / HTTP/1.1
x-amz-sns-message-type: SubscriptionConfirmation
x-amz-sns-message-id: 7de246b1-6459-4cf9-b5dc-e31d7e907ed5
x-amz-sns-topic-arn: arn:aws:sns:us-west-2:276428873250:magine-local
Content-Length: 1523
Content-Type: text/plain; charset=UTF-8
Host: dd9aa240.ngrok.io
User-Agent: Amazon Simple Notification Service Agent
Accept-Encoding: gzip,deflate
X-Forwarded-For: 205.251.233.166

{
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "7de246b1-6459-4cf9-b5dc-e31d7e907ed5",
  "Token" : "2336412f37fb687f5d51e6e241dbca52e99b16cd57bb154118abc86237328e922cb42fd3acc7ec6f7e4e88dc3b5e76f657a7ff53bd107fcc8dfb88fa0964a4d552b34afa420ec8222f0a0dd966b0d6691243c6cd1aa8691c99e7ce7f54708b5a932e1f5eb1359148b7f928eb0eb8e34d",
  "TopicArn" : "arn:aws:sns:us-west-2:276428873250:magine-local",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-west-2:276428873250:magine-local.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:276428873250:magine-local&Token=2336412f37fb687f5d51e6e241dbca52e99b16cd57bb154118abc86237328e922cb42fd3acc7ec6f7e4e88dc3b5e76f657a7ff53bd107fcc8dfb88fa0964a4d552b34afa420ec8222f0a0dd966b0d6691243c6cd1aa8691c99e7ce7f54708b5a932e1f5eb1359148b7f928eb0eb8e34d",
  "Timestamp" : "2019-06-24T19:15:08.225Z",
  "SignatureVersion" : "1",
  "Signature" : "S9w0aq+dxYLZ0T0wqk04vny1BIKKX3p5I26u081vejFbDzTDvKSOgwIfF4hfHaVY1YRDhHG6SJALnK2P8JlgGawy/iekix9ri1/3oeK5AIKA8uE2obqqKQ6xcogEMO30K9/82pj59FxwExHHG8JvRu5KIEp1DZENgTKDPY9yhpnp0JlXE7WtZaCAOlBvERbPbKJJO6nlM9hL0b2zEbVZW8c4Kp5YNEXfYlv7D/LMYPg6tU1yYKxTUja9nNHAHi5Yus28iZdeuLt0cN7IBdricOU2U9G7rZUNEjyOQZ8lFi6PV4/jHkkgUybLe91YWPy1s/rNOTDfOFMrRaP/xnGEpw==",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-6aad65c2f9911b05cd53efda11f913f9.pem"
}
```


Once subscribed the endpoint will recieve `Notification` requests whenever anything is published to the SNS Topic. Using the raw type you can send some JSON. (Looking into a better way to use `Content-Type application/json` here). Magine can use the [AWS SDK to publish the SNS message](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sns-examples-publishing-messages.html), I'll need to give the role these permissions.

```
POST / HTTP/1.1
x-amz-sns-message-type: Notification
x-amz-sns-message-id: 9c7278ec-d7f7-518c-bcb8-2d67f189033f
x-amz-sns-topic-arn: arn:aws:sns:us-west-2:276428873250:magine-local
x-amz-sns-subscription-arn: arn:aws:sns:us-west-2:276428873250:magine-local:76fa2f6c-d5f4-4d47-9501-570e76258fd1
x-amz-sns-rawdelivery: true
Content-Length: 81
Content-Type: text/plain; charset=UTF-8
Host: ea0c4a45.ngrok.io
User-Agent: Amazon Simple Notification Service Agent
Accept-Encoding: gzip,deflate
X-Forwarded-For: 54.240.230.176

{
  "hello": "world",
  "whatever": "you want",
  "sendIn": "this notification"
}
```
