### ISSUE TITLE
Separate Buckets into Read/Write

### ISSUE THREAD

**Issue by KempfCreative** [MaisonetteWorld/magine#39]
As part of #38, we are now expecting a bucket to listen to PUTs from and write the lambda code (READ bucket) and the bucket to put images to be served by the CDN (WRITE bucket). 

The current architecture expects a single bucket, which should be changed.

**Comment by KempfCreative** [comment]
@DanRoestorf can you help me by documenting the buckets we are actually using for the CDN? I can easily setup the process.env names, but I think we should have tiered storage.

E.G.
magine-dev -> media-dev.maisonette.com bucket
magine-staging -> media-stage.maisonette.com bucket
magine -> media.maisonette.com

**Comment by DanRoestorf** [comment]
The buckets are created through Terraform and the correct tier environment variables set when the Lambda function is created. The naming convention is fairly standard, CDN placed on the maisonette-* buckets.

magine-tst   > maisonette-tst
magine-dev > maisonette-dev
magine-stg  > maisonette-stg
magine-prd  > maisonette-prd

I still need to do a quick extraction of magine into a module for re-use per environment and move it into this project. You can see [here](https://github.com/MaisonetteWorld/terraformer/blob/a6940f02eb13f8eaee584335b422f0a066979292/apps/magine/dev/main.tf#L142) where the bucket is created, which is all based on the `environment` variable set [here](https://github.com/MaisonetteWorld/terraformer/blob/a6940f02eb13f8eaee584335b422f0a066979292/apps/magine/dev/main.tf#L24)

**Comment by DanRoestorf** [comment]
@KempfCreative you updated Magine to use separate buckets and I made the necessary changes in Terraform for the CDN. Good to close this issue?

**Comment by KempfCreative** [comment]
This can be closed I believe, yes
