### ISSUE TITLE
Increase hero image sizes

### ISSUE THREAD

**Issue by dinohamzic** [MaisonetteWorld/magine#69]
The image sizes of the hero module should be increased.

Currently on a Full-HD non-retina monitor the hero looks very pixelated.

For example this property https://github.com/MaisonetteWorld/magine/blob/master/lambda/options/hero_rules.json#L28 should be increased to 1920 (to match legacy)

Current pixelated state on staging:
![Screen Shot 2020-03-03 at 14 29 51](https://user-images.githubusercontent.com/31952489/75780352-76842400-5d5b-11ea-8d17-51a0b892ff1b.png)

**Comment by KempfCreative** [comment]
I will document each image on the homepage to start, and update the pixel dimensions accordingly.
